# mybayut_issues_only_audit_v7.py
# -*- coding: utf-8 -*-

import re
import time
import argparse
import os
import json
from collections import Counter
from difflib import SequenceMatcher
from pathlib import Path
from urllib.parse import urljoin, urlparse, urldefrag, unquote
import unicodedata
from concurrent.futures import ThreadPoolExecutor, as_completed

import pandas as pd
import requests
from bs4 import BeautifulSoup
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ============================================================
# SETTINGS
# ============================================================

INPUT_FILE = "articles.xlsx"
OUTPUT_FILE = "mybayut_issues_only_v7.xlsx"
CHECKPOINT_FILE = "mybayut_issues_checkpoint_v7.xlsx"

TITLE_COLUMN = "Title/Topic"
URL_COLUMN = "Live URL"

SITE_DOMAIN = "bayut.com"

REQUEST_TIMEOUT = 25
SLEEP_BETWEEN_ARTICLES = 0.05
SAVE_EVERY = 100

# ============================================================
# AI CONTENT QA + OFFICIAL-SOURCE VERIFICATION
# ============================================================
# This layer is enabled by default because it is the part that can distinguish:
#   FAIL   = proven error / official-source contradiction
#   REVIEW = insufficient official evidence / needs verification
#   PASS   = official source confirms the claim
# Set MYBAYUT_AI_CONTENT_QA=0 or use --no-ai-content to disable it.
AI_CONTENT_QA_DEFAULT = os.getenv("MYBAYUT_AI_CONTENT_QA", "1").strip().lower() not in {"0", "false", "no", "off"}
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
OPENAI_MODEL = os.getenv("MYBAYUT_AI_MODEL", "gpt-5.6").strip() or "gpt-5.6"
OPENAI_RESPONSES_URL = "https://api.openai.com/v1/responses"
AI_REQUEST_TIMEOUT = int(os.getenv("MYBAYUT_AI_TIMEOUT", "180"))
AI_MAX_ARTICLE_CHARS = int(os.getenv("MYBAYUT_AI_MAX_ARTICLE_CHARS", "45000"))

# Bayut is the article being audited, never the factual verification source.
# Obvious secondary/UGC/property-portal domains are blocked from AI web research.
AI_BLOCKED_SOURCE_DOMAINS = [
    "bayut.com", "dubizzle.com", "propertyfinder.ae", "wikipedia.org",
    "reddit.com", "tripadvisor.com", "quora.com", "pinterest.com",
    "facebook.com", "instagram.com", "linkedin.com", "youtube.com", "x.com",
]

AI_CONTENT_RULE_PREFIX = "Content QA: "

# ------------------------------------------------------------
# IMPORTANT
# Google does NOT publish an official list of "banned words".
# Add your own internal banned words here.
# ------------------------------------------------------------

BLOCKED_WORDS = [
    # Example:
    # "casino",
    # "كازينو",
]

# These phrases are NOT automatically spam.
# They only trigger REVIEW.
RISKY_PHRASES = []  # Disabled: Google has no official risky-phrases/banned-words list.

# Terms useful for detecting possible hacked/injected content.
INJECTION_RISK_TERMS = [
    # Gambling
    "casino", "gambling", "betting", "sportsbook", "poker", "slots",
    "كازينو", "قمار", "مقامرة", "مراهنات", "بوكر",

    # Adult / explicit
    "porn", "pornography", "xxx", "adult content",
    "إباحية", "اباحي", "محتوى إباحي",

    # Pharma / suspicious injected commercial terms
    "viagra", "cialis", "levitra", "payday loan", "payday loans",
    "crypto giveaway", "free crypto",

    # Strong profanity that would be unusual in normal MyBayut editorial copy
    "fuck", "fucking",
]

GENERIC_ANCHORS = {
    "click here",
    "here",
    "read more",
    "learn more",
    "more",
    "اضغط هنا",
    "هنا",
    "اقرأ المزيد",
    "اعرف المزيد",
    "المزيد",
}


# Common function/content words are excluded from keyword-stuffing checks.
ARABIC_STOPWORDS = {
    "التي","الذي","الذين","هذا","هذه","ذلك","تلك","هناك","كما","حيث","عند","على","إلى","الى",
    "من","في","عن","مع","أو","او","ثم","قد","تم","بعد","قبل","بين","ضمن","حول","خلال","يمكن",
    "يتم","تعد","يعد","تعتبر","يعتبر","أكثر","اقل","أقل","أبرز","وهي","وهو","وذلك","لدى","لها",
    "له","لهم","منها","منه","عليها","عليه","أيضا","أيضاً","كذلك","العديد","جميع","كل","غير",
    "حتى","إذا","اذا","ما","لا","لم","لن","أن","ان","إن","كان","كانت","يكون","تكون","أحد","احد",
    "الموقع","التواصل","صباحا","صباحًا","مساء","مساءً","دقائق","للقراءة","التحديث","تم"
}

ENGLISH_STOPWORDS = {
    "the","and","for","with","from","this","that","these","those","are","is","was","were","be",
    "been","being","to","of","in","on","at","by","or","as","an","a","it","its","you","your",
    "can","may","will","also","more","most","all","about","into","over","after","before",
    "their","they","them","our","we","has","have","had","not","but","if","than","which",
    "where","when","what","how","who","why","read","updated","minutes"
}

IGNORED_HIDDEN_TEXT = {
    "إلغاء التعليق", "cancel reply", "close", "menu", "search", "التالي", "السابق"
}

IGNORED_EXTERNAL_HOSTS = {
    "google.com", "www.google.com"
}

# Query/helper URLs generated by browsers/search UI are not editorial article links.
IGNORED_URL_PATTERNS = (
    "google.com/preferences/source",
    "/preferences/source",
)


# ============================================================
# ENTITY ACCURACY
# ============================================================

# Entity-type words help reduce false positives by focusing on likely
# buildings, projects, communities, developers, companies and places.
ENTITY_HINT_WORDS_EN = {
    "residence", "residences", "resident", "residents",
    "tower", "towers", "building", "buildings",
    "project", "projects", "development", "developments",
    "community", "communities", "district", "city",
    "marina", "harbour", "harbor", "hills", "estate", "estates",
    "gardens", "garden", "village", "villages",
    "park", "parks", "heights", "bay", "beach", "island", "islands",
    "mall", "malls", "hotel", "hotels", "resort", "resorts",
    "properties", "property", "realty", "group", "holding", "holdings",
    "development", "developer", "developers",
    "company", "companies", "centre", "center",
    "plaza", "square", "gate", "creek", "downtown",
    "golf", "club", "school", "academy", "hospital",
    "road", "street", "avenue"
}

ENTITY_HINT_WORDS_AR = {
    "برج", "أبراج", "ابراج", "مشروع", "مشاريع", "مجمع",
    "مدينة", "مارينا", "مرسى", "ميناء", "ميناء", "تلال",
    "قرية", "حدائق", "حديقة", "جزيرة", "جزر",
    "مول", "فندق", "فنادق", "منتجع", "منتجعات",
    "شركة", "شركات", "العقارية", "العقارية", "للتطوير",
    "التطوير", "القابضة", "مركز", "ميدان", "بوابة",
    "الخليج", "شاطئ", "شاطىء", "نادي", "مدرسة",
    "مستشفى", "شارع", "طريق"
}

# Very common leading words are ignored when they appear only because
# a sentence starts with a capital letter.
ENTITY_LEADING_STOPWORDS_EN = {
    "The", "This", "These", "Those", "Best", "Top", "Popular",
    "Most", "Another", "Other", "Some", "All", "Our", "Your"
}

ENTITY_SIMILARITY_REVIEW = 0.88
ENTITY_SIMILARITY_FAIL = 0.96

# ============================================================
# THRESHOLDS
# ============================================================

THIN_CONTENT_REVIEW = 250
THIN_CONTENT_FAIL = 100

KEYWORD_REPEAT_REVIEW = 20
KEYWORD_REPEAT_FAIL = 35

PHRASE_REPEAT_REVIEW = 8
PHRASE_REPEAT_FAIL = 15

LINK_DENSITY_REVIEW = 40   # links per 1000 words
LINK_DENSITY_FAIL = 70

SAME_TARGET_REVIEW = 4
SAME_TARGET_FAIL = 8

SAME_ANCHOR_REVIEW = 4
SAME_ANCHOR_FAIL = 8

SITE_TARGET_SHARE_REVIEW = 0.20
SITE_TARGET_SHARE_FAIL = 0.50

SITE_ANCHOR_TARGET_SHARE_REVIEW = 0.70
SITE_ANCHOR_TARGET_SHARE_FAIL = 0.90

# ============================================================
# HELPERS
# ============================================================

def clean_text(value):
    return re.sub(r"\s+", " ", str(value or "")).strip()

def normalize_url(url):
    url = clean_text(url)
    if not url:
        return ""
    return urldefrag(url)[0]


def comparable_url(url):
    """Normalize URL for equality checks without treating percent-encoding as a different URL."""
    url = normalize_url(url)
    if not url:
        return ""
    try:
        p = urlparse(url)
        scheme = (p.scheme or "https").lower()
        host = p.netloc.lower()
        if host == "bayut.com":
            host = "www.bayut.com"
        path = unicodedata.normalize("NFC", unquote(p.path or "/"))
        path = re.sub(r"/+", "/", path)
        if path != "/" and path.endswith("/"):
            path = path[:-1]
        return f"{scheme}://{host}{path}"
    except Exception:
        return unicodedata.normalize("NFC", unquote(url)).rstrip("/")

def ignored_url(url):
    low = (url or "").lower()
    return any(p in low for p in IGNORED_URL_PATTERNS)

def get_host(url):
    try:
        return urlparse(url).netloc.lower().split(":")[0]
    except Exception:
        return ""

def is_internal(url):
    host = get_host(url)
    return (
        host == SITE_DOMAIN
        or host == f"www.{SITE_DOMAIN}"
        or host.endswith(f".{SITE_DOMAIN}")
    )

def is_mybayut_article(url):
    try:
        return "/mybayut/" in urlparse(url).path.lower()
    except Exception:
        return False

def tokenize(text):
    return re.findall(r"[A-Za-z0-9\u0600-\u06FF]+", (text or "").lower())


def phrase_contexts(text, phrase, max_contexts=3, window=120):
    """
    Return short readable contexts around a matched phrase.
    Prefer sentence-like boundaries; fallback to a character window.
    """
    contexts = []
    low = text.lower()
    phrase_low = phrase.lower()
    start = 0

    while len(contexts) < max_contexts:
        idx = low.find(phrase_low, start)
        if idx == -1:
            break

        left = max(
            low.rfind(".", 0, idx),
            low.rfind("!", 0, idx),
            low.rfind("?", 0, idx),
            low.rfind("؟", 0, idx),
            low.rfind("،", max(0, idx - 180), idx),
        )
        right_candidates = [
            x for x in [
                low.find(".", idx + len(phrase_low)),
                low.find("!", idx + len(phrase_low)),
                low.find("?", idx + len(phrase_low)),
                low.find("؟", idx + len(phrase_low)),
            ] if x != -1
        ]

        if left == -1:
            left = max(0, idx - window)
        else:
            left += 1

        if right_candidates:
            right = min(right_candidates) + 1
            if right - left > 350:
                right = min(len(text), idx + len(phrase) + window)
        else:
            right = min(len(text), idx + len(phrase) + window)

        context = clean_text(text[left:right])
        if context and context not in contexts:
            contexts.append(context)

        start = idx + len(phrase_low)

    return contexts

def worst_status(statuses):
    rank = {"PASS": 0, "REVIEW": 1, "FAIL": 2}
    if not statuses:
        return "PASS"
    return max(statuses, key=lambda s: rank.get(s, 0))

def add_finding(
    rows, article_title, source_url, rule, status, why, evidence="", owner="",
    source_name="", official_source_url="", suggested_fix="",
    verification_basis="", source_type=""
):
    rows.append({
        "Title/Topic": article_title,
        "Source URL": source_url,
        "Rule": rule,
        "Status": status,
        "Why": why,
        "Evidence": evidence,
        "Responsible": owner,
        "Source Name": source_name,
        "Official Source URL": official_source_url,
        "Suggested Fix": suggested_fix,
        "Verification Basis": verification_basis,
        "Source Type": source_type,
    })

def extract_editorial_fields(body):
    """Extract content fields that visible_text() misses: headings, image ALT and captions."""
    headings = []
    image_alts = []
    image_captions = []

    if body is None:
        return {"headings": headings, "image_alts": image_alts, "image_captions": image_captions}

    for h in body.find_all(re.compile(r"^h[1-6]$")):
        value = clean_text(h.get_text(" "))
        if value:
            headings.append(f"{h.name.upper()}: {value}")

    for img in body.find_all("img"):
        alt = clean_text(img.get("alt", ""))
        if alt:
            image_alts.append(alt)

    for cap in body.find_all("figcaption"):
        value = clean_text(cap.get_text(" "))
        if value:
            image_captions.append(value)

    # WordPress/common caption classes that may not use <figcaption>.
    for node in body.select(".wp-caption-text, .caption, .image-caption, [class*='caption']"):
        value = clean_text(node.get_text(" "))
        if value and value not in image_captions:
            image_captions.append(value)

    return {
        "headings": list(dict.fromkeys(headings))[:120],
        "image_alts": list(dict.fromkeys(image_alts))[:200],
        "image_captions": list(dict.fromkeys(image_captions))[:200],
    }


def _collect_http_urls(obj):
    """Collect actual URLs returned by the Responses API/web-search payload."""
    urls = []
    if isinstance(obj, dict):
        for key, value in obj.items():
            if key == "url" and isinstance(value, str) and value.startswith(("http://", "https://")):
                urls.append(value)
            else:
                urls.extend(_collect_http_urls(value))
    elif isinstance(obj, list):
        for value in obj:
            urls.extend(_collect_http_urls(value))
    return list(dict.fromkeys(urls))


def _response_output_text(payload):
    """Extract assistant output_text from a raw Responses API JSON response."""
    for item in payload.get("output", []) or []:
        if not isinstance(item, dict) or item.get("type") != "message":
            continue
        for content in item.get("content", []) or []:
            if isinstance(content, dict) and content.get("type") == "output_text":
                return content.get("text", "") or ""
    return ""


def _host_without_www(url):
    host = get_host(url)
    return host[4:] if host.startswith("www.") else host


def _is_blocked_verification_source(url):
    host = _host_without_www(url)
    if not host:
        return True
    return any(host == d or host.endswith("." + d) for d in AI_BLOCKED_SOURCE_DOMAINS)


def _reconcile_with_web_source(candidate_url, web_urls):
    """
    Never trust a model-written source URL blindly.
    Keep it only when the Responses web-search payload actually consulted that URL/domain.
    If the exact URL is absent but the same official domain was consulted, return the real
    consulted URL from the API payload instead of a potentially invented path.
    """
    candidate_url = clean_text(candidate_url)
    if not candidate_url or _is_blocked_verification_source(candidate_url):
        return ""

    candidate_cmp = comparable_url(candidate_url)
    for url in web_urls:
        if comparable_url(url) == candidate_cmp and not _is_blocked_verification_source(url):
            return url

    candidate_host = _host_without_www(candidate_url)
    same_host = [
        url for url in web_urls
        if _host_without_www(url) == candidate_host
        and not _is_blocked_verification_source(url)
    ]
    return same_host[0] if same_host else ""


def _content_qa_schema():
    return {
        "type": "object",
        "properties": {
            "findings": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "status": {"type": "string", "enum": ["PASS", "REVIEW", "FAIL"]},
                        "check": {
                            "type": "string",
                            "enum": [
                                "Factual Accuracy", "Entity Accuracy", "Grammar & Wording",
                                "Search Intent", "Image Alt Text", "Image Caption"
                            ]
                        },
                        "issue_name": {"type": "string"},
                        "result": {"type": "string"},
                        "article_excerpt": {"type": "string"},
                        "correction": {"type": "string"},
                        "verification_basis": {
                            "type": "string",
                            "enum": ["official_source", "article_text", "insufficient_official_evidence"]
                        },
                        "source_name": {"type": "string"},
                        "source_url": {"type": "string"},
                        "source_type": {
                            "type": "string",
                            "enum": [
                                "government", "official_developer", "official_project",
                                "official_organisation", "official_business", "article_itself", "none"
                            ]
                        }
                    },
                    "required": [
                        "status", "check", "issue_name", "result", "article_excerpt", "correction",
                        "verification_basis", "source_name", "source_url", "source_type"
                    ],
                    "additionalProperties": False
                }
            }
        },
        "required": ["findings"],
        "additionalProperties": False
    }


def _content_qa_prompt(article_title, source_url, text, editorial_fields):
    article_text = (text or "")[:AI_MAX_ARTICLE_CHARS]
    headings = "\n".join(editorial_fields.get("headings", [])[:120]) or "(none extracted)"
    alts = "\n".join(f"- {x}" for x in editorial_fields.get("image_alts", [])[:200]) or "(none extracted)"
    captions = "\n".join(f"- {x}" for x in editorial_fields.get("image_captions", [])[:200]) or "(none extracted)"

    return f"""You are the Content QA engine for a MyBayut article. Audit CONTENT only.

ARTICLE TITLE:
{article_title}

ARTICLE URL (evidence only, NEVER use Bayut as a factual verification source):
{source_url}

NON-NEGOTIABLE VERIFICATION POLICY:
1. For factual claims, entity names, project/building/community details, awards, unit counts, floor counts,
   completion years, developers, amenities, certifications, distances and similar facts, research the web.
2. Use OFFICIAL/PRIMARY sources only whenever available, in this priority:
   UAE government / Dubai Land Department / RERA / other government authority; official developer;
   official project/community; official school/hospital/attraction/golf club/business/company website.
3. NEVER use Bayut, Dubizzle, Property Finder, Wikipedia, Reddit, TripAdvisor, brokers, property portals,
   aggregators, blogs or SEO sites to confirm a factual claim.
4. FAIL a factual claim ONLY when an authoritative official source directly contradicts it.
5. REVIEW when official public evidence is insufficient to confirm or contradict the claim. Lack of evidence
   is NOT proof that the article is wrong.
6. PASS only when an official source directly confirms the claim. Include useful PASS findings when they
   prevent an incorrect flag, e.g. a claim that looked suspicious but is officially confirmed.
7. Grammar, spelling, wording and search-intent problems can be FAIL based on article_text alone; they do
   not need external verification.
8. Do not invent corrections, unit counts, dates, awards, certifications or URLs.
9. Inspect image ALT text and captions separately for entity errors, grammar and factual claims.
10. For numerical wording, never mix average with minimum/starting price. Example: "average ... starts from"
    is wrong wording; use "average is" for an average or "starts from" for a minimum.
11. Search intent: if the article is rental-focused, a substantial investment/buying FAQ is off-intent.
12. Make each result concise but specific, like: what is wrong, what the official evidence says, and exactly
    what to change. For REVIEW say clearly that the claim needs verification and must not be called false.
13. Do not output generic statements such as "check this" or "may be wrong".
14. Return no more than 20 high-value findings. Precision is more important than quantity.

STATUS SEMANTICS:
PASS = No issue / officially confirmed.
REVIEW = Needs verification / official evidence insufficient.
FAIL = Proven factual/content/entity/grammar/search-intent error.

HEADINGS:
{headings}

IMAGE ALT TEXT:
{alts}

IMAGE CAPTIONS:
{captions}

ARTICLE TEXT:
{article_text}
"""


def ai_content_qa_checks(article_title, source_url, text, body, findings):
    """Run one structured, web-grounded content QA pass for the article."""
    editorial_fields = extract_editorial_fields(body)
    prompt = _content_qa_prompt(article_title, source_url, text, editorial_fields)

    payload = {
        "model": OPENAI_MODEL,
        "reasoning": {"effort": "medium"},
        "tools": [
            {
                "type": "web_search",
                "filters": {"blocked_domains": AI_BLOCKED_SOURCE_DOMAINS},
            }
        ],
        "tool_choice": "auto",
        "include": ["web_search_call.action.sources"],
        "input": [
            {
                "role": "system",
                "content": (
                    "Return a precise MyBayut Content QA. Follow the official-source policy strictly. "
                    "A missing source is not proof of falsehood."
                ),
            },
            {"role": "user", "content": prompt},
        ],
        "text": {
            "format": {
                "type": "json_schema",
                "name": "mybayut_content_qa",
                "strict": True,
                "schema": _content_qa_schema(),
            }
        },
    }

    r = requests.post(
        OPENAI_RESPONSES_URL,
        headers={
            "Authorization": f"Bearer {OPENAI_API_KEY}",
            "Content-Type": "application/json",
        },
        json=payload,
        timeout=AI_REQUEST_TIMEOUT,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"OpenAI Content QA HTTP {r.status_code}: {r.text[:500]}")

    response_payload = r.json()
    output_text = _response_output_text(response_payload)
    if not output_text:
        raise RuntimeError("OpenAI Content QA returned no output_text.")

    parsed = json.loads(output_text)
    web_urls = _collect_http_urls(response_payload)
    statuses = []

    factual_checks = {"Factual Accuracy", "Entity Accuracy"}

    for item in parsed.get("findings", [])[:20]:
        status = item.get("status", "REVIEW")
        check = clean_text(item.get("check", "Factual Accuracy"))
        issue_name = clean_text(item.get("issue_name", check)) or check
        result_text = clean_text(item.get("result", ""))
        excerpt = clean_text(item.get("article_excerpt", ""))
        correction = clean_text(item.get("correction", ""))
        basis = clean_text(item.get("verification_basis", ""))
        source_name = clean_text(item.get("source_name", ""))
        source_type = clean_text(item.get("source_type", "none"))
        model_source_url = clean_text(item.get("source_url", ""))
        source_url_verified = _reconcile_with_web_source(model_source_url, web_urls)

        # Image ALT/caption findings can be either editorial or factual/entity based.
        content_only = check in {"Grammar & Wording", "Search Intent"}
        if check in {"Image Alt Text", "Image Caption"} and basis == "article_text":
            content_only = True

        # Enforce evidence semantics even if the model overstates certainty.
        if not content_only:
            if status == "FAIL" and basis != "official_source":
                status = "REVIEW"
                basis = "insufficient_official_evidence"
                result_text = (
                    "Needs verification. The available result did not contain authoritative official evidence "
                    "that directly contradicts this claim, so it must not be labelled incorrect."
                )
            elif status == "PASS" and basis != "official_source":
                status = "REVIEW"
                basis = "insufficient_official_evidence"
                result_text = (
                    "Needs verification. No authoritative official source was established strongly enough to "
                    "confirm this claim."
                )

            if basis == "official_source" and not source_url_verified:
                if status in {"FAIL", "PASS"}:
                    status = "REVIEW"
                    basis = "insufficient_official_evidence"
                    result_text = (
                        "Needs verification. The model did not provide an official source URL that could be "
                        "matched to the web-search sources actually consulted, so the claim cannot be marked "
                        "incorrect or confirmed."
                    )
                source_name = ""
                source_type = "none"

        # For article-text-only errors, external source fields should remain empty/clean.
        if content_only:
            source_url_verified = ""
            if source_type == "none":
                source_type = "article_itself"
            if not source_name:
                source_name = "Article content"

        evidence_parts = []
        if excerpt:
            evidence_parts.append(f"Article: {excerpt}")
        if source_url_verified:
            evidence_parts.append(f"Official source: {source_url_verified}")
        evidence = " | ".join(evidence_parts)

        # Preserve the user's preferred natural-language result as the primary explanation.
        why = result_text or issue_name
        if correction and correction.lower() not in why.lower():
            why = f"{why} Suggested correction: {correction}"

        add_finding(
            findings,
            article_title,
            source_url,
            AI_CONTENT_RULE_PREFIX + check,
            status,
            why,
            evidence,
            "Content / Editor",
            source_name=source_name,
            official_source_url=source_url_verified,
            suggested_fix=correction,
            verification_basis=basis,
            source_type=source_type,
        )
        statuses.append(status)

    return statuses


def build_content_qa_sheet(finding_rows):
    """User-facing Content QA sheet with PASS/REVIEW/FAIL and source-backed explanations."""
    if not finding_rows:
        return pd.DataFrame(columns=[
            "Title/Topic", "Article URL", "Status", "Check", "Result", "Article Evidence",
            "Source Name", "Official Source URL", "Source Type", "Suggested Fix", "Verification Basis"
        ])

    df = pd.DataFrame(finding_rows)
    if df.empty or "Rule" not in df.columns:
        return pd.DataFrame()

    df = df[df["Rule"].fillna("").str.startswith(AI_CONTENT_RULE_PREFIX)].copy()
    if df.empty:
        return pd.DataFrame(columns=[
            "Title/Topic", "Article URL", "Status", "Check", "Result", "Article Evidence",
            "Source Name", "Official Source URL", "Source Type", "Suggested Fix", "Verification Basis"
        ])

    out = pd.DataFrame({
        "Title/Topic": df.get("Title/Topic", ""),
        "Article URL": df.get("Source URL", ""),
        "Status": df.get("Status", ""),
        "Check": df.get("Rule", "").str.replace(AI_CONTENT_RULE_PREFIX, "", regex=False),
        "Result": df.get("Why", ""),
        "Article Evidence": df.get("Evidence", ""),
        "Source Name": df.get("Source Name", ""),
        "Official Source URL": df.get("Official Source URL", ""),
        "Source Type": df.get("Source Type", ""),
        "Suggested Fix": df.get("Suggested Fix", ""),
        "Verification Basis": df.get("Verification Basis", ""),
    })

    priority = {"FAIL": 0, "REVIEW": 1, "PASS": 2}
    out["_priority"] = out["Status"].map(priority).fillna(9)
    out = out.sort_values(["_priority", "Title/Topic", "Check"]).drop(columns=["_priority"])
    return out.reset_index(drop=True)


def build_session():
    s = requests.Session()
    retry = Retry(
        total=3,
        connect=3,
        read=3,
        status=3,
        backoff_factor=0.7,
        status_forcelist=(429, 500, 502, 503, 504),
        allowed_methods=frozenset(["GET", "HEAD"]),
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=50, pool_maxsize=50)
    s.mount("http://", adapter)
    s.mount("https://", adapter)
    s.headers.update({
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/151.0.0.0 Safari/537.36"
        ),
        "Accept-Language": "en-US,en;q=0.9,ar;q=0.8",
    })
    return s

def fetch(session, url):
    try:
        r = session.get(url, timeout=REQUEST_TIMEOUT, allow_redirects=True)
        return {
            "ok": True,
            "response": r,
            "status": r.status_code,
            "final_url": r.url,
            "redirect_count": len(r.history),
            "redirect_chain": " > ".join(
                [str(x.status_code) for x in r.history] + [str(r.status_code)]
            ),
            "error": "",
        }
    except Exception as e:
        return {
            "ok": False,
            "response": None,
            "status": None,
            "final_url": "",
            "redirect_count": 0,
            "redirect_chain": "",
            "error": f"{type(e).__name__}: {e}",
        }

def visible_text(node):
    if node is None:
        return ""
    clone = BeautifulSoup(str(node), "html.parser")
    for tag in clone(["script", "style", "noscript", "template", "svg"]):
        tag.decompose()
    return clean_text(clone.get_text(" "))

def find_article_body(soup):
    selectors = [
        "[itemprop='articleBody']",
        ".article-content",
        ".entry-content",
        ".post-content",
        "article .content",
        "article",
        "main article",
        ".blog-detail",
        "main",
        "[role='main']",
    ]
    candidates = []
    for selector in selectors:
        try:
            for node in soup.select(selector):
                txt = visible_text(node)
                if len(txt) > 200:
                    candidates.append((len(txt), node))
        except Exception:
            pass

    node = candidates[0][1] if candidates else (soup.body or soup)

    # Work on a clone so UI cleanup does not alter the original soup used for metadata checks.
    node = BeautifulSoup(str(node), "html.parser")

    # Strip common non-editorial UI blocks that otherwise create false link/text signals.
    ui_selectors = [
        "nav", "header", "footer",
        ".breadcrumb", ".breadcrumbs",
        ".social-share", ".share", ".sharing",
        ".comments", "#comments", ".comment-respond", "#respond",
        ".author-box", ".author-info",
        ".related-posts", ".related-articles",
        ".newsletter", ".subscribe",
        "[aria-label='breadcrumb']",
        "[role='navigation']"
    ]
    for sel in ui_selectors:
        for x in node.select(sel):
            x.decompose()

    return node

def extract_links(body, source_url):
    rows = []
    for a in body.find_all("a", href=True):
        href = clean_text(a.get("href", ""))
        if not href:
            continue
        if href.startswith(("mailto:", "tel:", "javascript:", "#")):
            continue

        target = normalize_url(urljoin(source_url, href))
        if ignored_url(target):
            continue

        anchor_text = clean_text(a.get_text(" "))
        accessible_label = clean_text(a.get("aria-label", "") or a.get("title", ""))

        # Icon/image-only links are not treated as empty editorial anchors.
        has_visual = bool(a.find(["img", "svg", "use"]))
        if not anchor_text and has_visual:
            continue
        if not anchor_text and accessible_label:
            anchor_text = accessible_label

        rows.append({
            "Source URL": source_url,
            "Anchor Text": anchor_text,
            "Target URL": target,
            "Target Host": get_host(target),
            "Internal": is_internal(target),
            "Rel": " ".join(a.get("rel") or []).lower(),
        })
    return rows

def find_hidden_content(soup):
    hits = []

    css_patterns = [
        r"display\s*:\s*none",
        r"visibility\s*:\s*hidden",
        r"opacity\s*:\s*0(?:[;\s]|$)",
        r"font-size\s*:\s*0(?:px|em|rem|%)?",
        r"text-indent\s*:\s*-\d{3,}",
        r"left\s*:\s*-\d{3,}",
    ]

    for tag in soup.find_all(True):
        style = (tag.get("style") or "").lower()

        hidden = (
            tag.has_attr("hidden")
            or (tag.get("aria-hidden") or "").lower() == "true"
            or any(re.search(p, style) for p in css_patterns)
        )

        if hidden:
            txt = clean_text(tag.get_text(" "))
            links = tag.find_all("a", href=True)

            meaningful_links = [a for a in links if a.get("href") and not str(a.get("href")).startswith("#")]
            normalized_txt = txt.strip().lower()

            if normalized_txt in {x.lower() for x in IGNORED_HIDDEN_TEXT}:
                continue

            # Ignore short hidden UI labels with no real outbound/internal href.
            suspicious_text = len(txt) >= 80 or any(
                term.lower() in normalized_txt for term in INJECTION_RISK_TERMS
            )

            if meaningful_links or suspicious_text:
                hits.append(
                    f"<{tag.name}> text={txt[:120]!r}; links={len(meaningful_links)}; style={style[:100]!r}"
                )

    return hits


def normalize_entity_name(name):
    """
    Normalize an entity for comparison without hiding real spelling differences.
    """
    value = unicodedata.normalize("NFC", clean_text(name)).lower()
    value = unquote(value)
    value = re.sub(r"[’'`´]", "", value)
    value = re.sub(r"[^0-9a-z\u0600-\u06FF\s&-]", " ", value)
    value = value.replace("&", " and ")
    value = re.sub(r"[-_/]+", " ", value)
    value = re.sub(r"\s+", " ", value).strip()
    return value


def entity_tokens(name):
    return [
        x for x in re.findall(r"[0-9A-Za-z\u0600-\u06FF]+", name)
        if x
    ]


def likely_entity_candidate(name):
    name = clean_text(name)
    if len(name) < 5 or len(name) > 100:
        return False

    toks = entity_tokens(name)
    if len(toks) < 2 or len(toks) > 7:
        return False

    low_tokens = {x.lower() for x in toks}

    # Strong hint: entity-type word is present.
    if low_tokens & ENTITY_HINT_WORDS_EN:
        return True
    if low_tokens & ENTITY_HINT_WORDS_AR:
        return True

    # For English, allow 2-5 title-cased proper-name tokens.
    latin_tokens = [x for x in toks if re.search(r"[A-Za-z]", x)]
    if len(latin_tokens) >= 2:
        title_like = sum(
            1 for x in latin_tokens
            if x[:1].isupper() or x.isupper()
        )
        if title_like == len(latin_tokens):
            if toks[0] not in ENTITY_LEADING_STOPWORDS_EN:
                return True

    return False


def extract_entity_candidates(text):
    """
    Lightweight proper-noun/entity extraction without external NLP packages.

    English:
      Finds sequences such as:
      Elite Sports Residence
      Dubai Marina
      Emaar Properties

    Arabic:
      Finds short phrases around entity-type terms such as برج، مجمع، شركة، مدينة...
      This is intentionally conservative to avoid flooding the audit.
    """
    candidates = []

    # English / Latin-script proper names: 2-7 tokens.
    en_pattern = re.compile(
        r"\b(?:[A-Z][A-Za-z0-9&'’.-]*|[A-Z]{2,}|[0-9]+)"
        r"(?:\s+(?:[A-Z][A-Za-z0-9&'’.-]*|[A-Z]{2,}|[0-9]+)){1,6}\b"
    )

    for m in en_pattern.finditer(text):
        name = clean_text(m.group(0))
        if likely_entity_candidate(name):
            candidates.append(name)

    # Arabic: capture a conservative 2-5 word window containing a known hint term.
    ar_words = re.findall(r"[\u0600-\u06FF0-9]+", text)
    for i, word in enumerate(ar_words):
        if word in ENTITY_HINT_WORDS_AR:
            for left, right in [(1, 2), (0, 3)]:
                start = max(0, i - left)
                end = min(len(ar_words), i + right + 1)
                phrase = " ".join(ar_words[start:end])
                toks = entity_tokens(phrase)
                if 2 <= len(toks) <= 5:
                    candidates.append(phrase)

    # Preserve original spellings while deduplicating exact forms.
    return list(dict.fromkeys(candidates))


def entity_pair_similarity(a, b):
    na = normalize_entity_name(a)
    nb = normalize_entity_name(b)

    if not na or not nb or na == nb:
        return 0.0

    # Character similarity
    char_score = SequenceMatcher(None, na, nb).ratio()

    # Token overlap helps avoid unrelated names with coincidentally similar strings.
    ta = na.split()
    tb = nb.split()
    set_a, set_b = set(ta), set(tb)
    union = set_a | set_b
    token_jaccard = len(set_a & set_b) / max(len(union), 1)

    # Prefer same-length or nearly same-length names.
    length_penalty = 1.0
    if abs(len(ta) - len(tb)) > 1:
        length_penalty = 0.85

    # Weighted score.
    score = (char_score * 0.75 + token_jaccard * 0.25) * length_penalty
    return score


def entity_accuracy_checks(article_title, source_url, text, findings):
    """
    Flags near-duplicate entity names in the same article.

    Example:
      Elite Sports Residence
      Elite Sports Residents

    This does not decide which spelling is correct. It flags the pair for review.
    """
    statuses = []

    candidates = extract_entity_candidates(text)

    # Count occurrences using exact visible forms.
    occurrence_counts = {
        c: len(re.findall(re.escape(c), text, flags=re.I))
        for c in candidates
    }

    suspicious_pairs = []
    seen_pairs = set()

    for i in range(len(candidates)):
        for j in range(i + 1, len(candidates)):
            a = candidates[i]
            b = candidates[j]

            na = normalize_entity_name(a)
            nb = normalize_entity_name(b)

            if na == nb:
                continue

            ta = na.split()
            tb = nb.split()

            # Keep comparisons local: broadly similar name length/token structure.
            if abs(len(ta) - len(tb)) > 1:
                continue

            # At least one shared meaningful token is required.
            shared = set(ta) & set(tb)
            shared = {
                x for x in shared
                if len(x) >= 3
                and x not in ARABIC_STOPWORDS
                and x not in ENGLISH_STOPWORDS
            }
            if not shared:
                continue

            score = entity_pair_similarity(a, b)

            if score < ENTITY_SIMILARITY_REVIEW:
                continue

            pair_key = tuple(sorted((na, nb)))
            if pair_key in seen_pairs:
                continue
            seen_pairs.add(pair_key)

            suspicious_pairs.append({
                "name_a": a,
                "name_b": b,
                "norm_a": na,
                "norm_b": nb,
                "count_a": occurrence_counts.get(a, 0),
                "count_b": occurrence_counts.get(b, 0),
                "score": score,
            })

    if suspicious_pairs:
        # The highest-confidence pair determines the rule severity.
        max_score = max(x["score"] for x in suspicious_pairs)
        status = "FAIL" if max_score >= ENTITY_SIMILARITY_FAIL else "REVIEW"

        evidence_parts = []
        for p in sorted(
            suspicious_pairs,
            key=lambda x: x["score"],
            reverse=True
        )[:10]:
            evidence_parts.append(
                f"{p['name_a']!r} ({p['count_a']}x) <> "
                f"{p['name_b']!r} ({p['count_b']}x) | "
                f"similarity={p['score']:.1%} | "
                f"normalized={p['norm_a']!r} <> {p['norm_b']!r}"
            )

        add_finding(
            findings,
            article_title,
            source_url,
            "Entity Accuracy",
            status,
            (
                "Near-duplicate entity names were found in the same article. "
                "One form may be a typo or inconsistent naming. "
                "The audit flags the inconsistency but does not automatically decide which name is correct."
            ),
            " | ".join(evidence_parts),
            "Content / Editor"
        )
        statuses.append(status)
    else:
        add_finding(
            findings,
            article_title,
            source_url,
            "Entity Accuracy",
            "PASS",
            "No suspicious near-duplicate entity-name variants were detected.",
            "",
            "Content / Editor"
        )
        statuses.append("PASS")

    return statuses

# ============================================================
# CONTENT CHECKS
# ============================================================

def content_checks(article_title, source_url, text, findings):
    statuses = []
    low = text.lower()
    words = tokenize(text)
    word_count = len(words)

    # Thin content
    if word_count < THIN_CONTENT_FAIL:
        status = "FAIL"
    elif word_count < THIN_CONTENT_REVIEW:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Thin Content",
        status,
        "Checks whether the visible article content is unusually short.",
        f"Word Count = {word_count}",
        "Content"
    )
    statuses.append(status)

    # Blocked words
    blocked_hits = []
    for phrase in BLOCKED_WORDS:
        count = low.count(phrase.lower())
        if count:
            blocked_hits.append(f"{phrase} ({count})")

    status = "FAIL" if blocked_hits else "PASS"
    add_finding(
        findings, article_title, source_url,
        "Internal Blocked Words",
        status,
        "Matches MyBayut's own internal prohibited-word list. This is not a Google banned-word list.",
        ", ".join(blocked_hits[:30]),
        "Content / Editor"
    )
    statuses.append(status)

    # Risky phrases
    risky_hits = []
    risky_evidence = []

    for phrase in RISKY_PHRASES:
        count = low.count(phrase.lower())
        if count:
            contexts = phrase_contexts(text, phrase, max_contexts=2)
            risky_hits.append({
                "phrase": phrase,
                "count": count,
                "contexts": contexts,
            })

            if contexts:
                risky_evidence.append(
                    f"Matched phrase: {phrase!r} | Count: {count} | "
                    f"Context: " + " || ".join(contexts)
                )
            else:
                risky_evidence.append(
                    f"Matched phrase: {phrase!r} | Count: {count}"
                )

    # This rule is intentionally disabled because Google does not publish
    # an official risky-phrases or banned-words list.

    # Suspicious / unexpected terms
    suspicious_hits = []
    suspicious_evidence = []

    for phrase in INJECTION_RISK_TERMS:
        count = low.count(phrase.lower())
        if count:
            contexts = phrase_contexts(text, phrase, max_contexts=3)
            suspicious_hits.append((phrase, count))
            suspicious_evidence.append(
                f"Term: {phrase!r} | Count: {count} | Context: "
                + (" || ".join(contexts) if contexts else "Context unavailable")
            )

    status = "REVIEW" if suspicious_hits else "PASS"

    add_finding(
        findings,
        article_title,
        source_url,
        "Suspicious / Unexpected Terms",
        status,
        (
            "One or more terms unusual for normal MyBayut editorial content were detected. "
            "Review the context for possible hacked/injected, inappropriate, or off-topic content. "
            "A detected term is not automatically a Google spam violation."
            if suspicious_hits else
            "No configured suspicious/unexpected terms were detected."
        ),
        " | ".join(suspicious_evidence[:30]),
        "Content / Backend"
    )
    statuses.append(status)

    # Keyword repetition
    stopwords = ARABIC_STOPWORDS | ENGLISH_STOPWORDS
    counts = Counter(
        w for w in words
        if len(w) >= 4
        and not w.isdigit()
        and w not in stopwords
    )

    candidates = []
    for w, n in counts.most_common(40):
        density = (n / max(word_count, 1)) * 100
        if n >= KEYWORD_REPEAT_REVIEW and density >= 2.0:
            candidates.append((w, n, density))

    max_density = max((d for _, _, d in candidates), default=0)
    max_repeat = max((n for _, n, _ in candidates), default=0)

    # Requires both unusually high frequency AND meaningful density.
    if max_repeat >= KEYWORD_REPEAT_FAIL and max_density >= 3.5:
        status = "FAIL"
    elif candidates:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Keyword Repetition",
        status,
        "Checks unusually concentrated non-stopword terms. Raw repetition alone is not treated as spam.",
        ", ".join(f"{w}={n} ({d:.1f}%)" for w, n, d in candidates[:15]),
        "Content / SEO"
    )
    statuses.append(status)

    # Repeated 5-word phrases, excluding common page boilerplate.
    grams = Counter(
        " ".join(words[i:i+5])
        for i in range(max(0, len(words) - 4))
    )
    boilerplate_fragments = (
        "دقائق للقراءة", "تم التحديث", "minutes read", "last updated"
    )
    repeated_phrases = [
        (p, n) for p, n in grams.most_common(30)
        if n >= PHRASE_REPEAT_REVIEW
        and not any(b in p for b in boilerplate_fragments)
    ]

    max_phrase_repeat = repeated_phrases[0][1] if repeated_phrases else 0

    if max_phrase_repeat >= PHRASE_REPEAT_FAIL:
        status = "FAIL"
    elif max_phrase_repeat >= PHRASE_REPEAT_REVIEW:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Repeated Phrases",
        status,
        "Checks for heavily repeated five-word phrases after excluding common page boilerplate.",
        " | ".join(f"{p!r}={n}" for p, n in repeated_phrases[:10]),
        "Content / SEO"
    )
    statuses.append(status)

    return statuses, word_count

# ============================================================
# TECHNICAL CHECKS
# ============================================================

def technical_checks(article_title, source_url, soup, findings):
    statuses = []

    # Meta robots
    robots = soup.find("meta", attrs={"name": re.compile("^robots$", re.I)})
    robots_value = (robots.get("content", "") if robots else "").lower()

    status = "REVIEW" if "noindex" in robots_value else "PASS"
    add_finding(
        findings, article_title, source_url,
        "Meta Robots",
        status,
        "Checks whether the article is marked noindex.",
        robots_value,
        "SEO / Backend"
    )
    statuses.append(status)

    # Canonical
    canonical_tag = soup.find(
        "link",
        attrs={"rel": lambda v: v and "canonical" in [
            x.lower() for x in (v if isinstance(v, list) else [v])
        ]}
    )

    canonical = normalize_url(
        canonical_tag.get("href", "")
    ) if canonical_tag else ""

    if not canonical:
        status = "REVIEW"
        why = "Canonical tag is missing."
    elif comparable_url(canonical) != comparable_url(source_url):
        status = "REVIEW"
        why = "Canonical points to a genuinely different URL."
    else:
        status = "PASS"
        why = "Canonical matches the source URL."

    add_finding(
        findings, article_title, source_url,
        "Canonical",
        status,
        why,
        canonical,
        "SEO / Backend"
    )
    statuses.append(status)

    # H1
    h1s = [clean_text(x.get_text(" ")) for x in soup.find_all("h1")]

    status = "PASS" if len(h1s) == 1 else "REVIEW"
    add_finding(
        findings, article_title, source_url,
        "H1",
        status,
        "Checks for missing or multiple H1 elements.",
        f"Count={len(h1s)} | " + " || ".join(h1s[:5]),
        "Content / SEO"
    )
    statuses.append(status)

    # Hidden content
    hidden_hits = find_hidden_content(soup)
    status = "REVIEW" if hidden_hits else "PASS"

    add_finding(
        findings, article_title, source_url,
        "Hidden Text / Hidden Links",
        status,
        "Static HTML contains hidden text or links. Some hidden UI is legitimate, so manual review is required.",
        " | ".join(hidden_hits[:10]),
        "Backend / SEO"
    )
    statuses.append(status)

    return statuses, canonical, robots_value, h1s

# ============================================================
# LINK CHECKS
# ============================================================

def page_link_checks(article_title, source_url, links, word_count, findings):
    statuses = []

    total_links = len(links)
    internal_links = sum(1 for x in links if x["Internal"])
    external_links = total_links - internal_links

    density = total_links / max(word_count, 1) * 1000

    if density >= LINK_DENSITY_FAIL:
        status = "FAIL"
    elif density >= LINK_DENSITY_REVIEW:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Link Density",
        status,
        "Checks whether article-body link volume is unusually high compared with content length.",
        f"Total={total_links}; Internal={internal_links}; External={external_links}; Links/1000 words={density:.1f}",
        "SEO / Content"
    )
    statuses.append(status)

    # Generic anchors
    generic = [
        x for x in links
        if x["Anchor Text"].strip().lower() in GENERIC_ANCHORS
    ]

    status = "REVIEW" if generic else "PASS"
    add_finding(
        findings, article_title, source_url,
        "Generic Anchor Text",
        status,
        "Checks for vague anchor text such as 'click here' or 'اضغط هنا'.",
        " | ".join(
            f"{x['Anchor Text']} -> {x['Target URL']}"
            for x in generic[:10]
        ),
        "Content / SEO"
    )
    statuses.append(status)

    # Empty anchors
    empty = [x for x in links if not x["Anchor Text"].strip()]

    status = "REVIEW" if empty else "PASS"
    add_finding(
        findings, article_title, source_url,
        "Empty Anchor Text",
        status,
        "Text links with no visible or accessible anchor label were detected.",
        f"Count={len(empty)}",
        "Content / SEO"
    )
    statuses.append(status)

    # Repeated targets
    target_counts = Counter(x["Target URL"] for x in links)
    top_target = target_counts.most_common(1)[0] if target_counts else ("", 0)

    if top_target[1] >= SAME_TARGET_FAIL:
        status = "FAIL"
    elif top_target[1] >= SAME_TARGET_REVIEW:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Repeated Target in Same Article",
        status,
        "Checks whether the same destination URL is linked excessively within one article.",
        f"{top_target[0]} => {top_target[1]} links" if top_target[1] else "",
        "SEO / Content"
    )
    statuses.append(status)

    # Repeated anchors
    anchor_counts = Counter(
        x["Anchor Text"].lower()
        for x in links
        if x["Anchor Text"]
    )
    top_anchor = anchor_counts.most_common(1)[0] if anchor_counts else ("", 0)

    if top_anchor[1] >= SAME_ANCHOR_FAIL:
        status = "FAIL"
    elif top_anchor[1] >= SAME_ANCHOR_REVIEW:
        status = "REVIEW"
    else:
        status = "PASS"

    add_finding(
        findings, article_title, source_url,
        "Repeated Anchor in Same Article",
        status,
        "Checks whether the same anchor text is repeated excessively within one article.",
        f"{top_anchor[0]!r} => {top_anchor[1]} uses" if top_anchor[1] else "",
        "SEO / Content"
    )
    statuses.append(status)

    return statuses

# ============================================================
# CHECKPOINT
# ============================================================

def build_issues_only(article_rows, finding_rows, link_rows):
    """
    One row per actionable issue.
    PASS rows are excluded.
    Link issues contain the exact problematic URL and redirect/broken-link details.
    """
    articles_df = pd.DataFrame(article_rows)
    findings_df = pd.DataFrame(finding_rows)
    links_df = pd.DataFrame(link_rows)

    issue_rows = []

    article_lookup = {}
    if not articles_df.empty and "Source URL" in articles_df.columns:
        article_lookup = {
            r["Source URL"]: r
            for _, r in articles_df.iterrows()
        }

    # Non-link findings.
    # Broken/redirect findings are represented below from link_rows so that
    # the exact wrong URL, anchor, final URL and HTTP details are visible.
    link_aggregate_rules = {
        "Broken Links",
        "Internal Redirect Links",
    }

    if not findings_df.empty:
        bad_findings = findings_df[
            (findings_df["Status"] != "PASS")
            & (~findings_df["Rule"].isin(link_aggregate_rules))
        ].copy()

        for _, f in bad_findings.iterrows():
            article = article_lookup.get(f["Source URL"], {})
            issue_rows.append({
                "Title/Topic": f.get("Title/Topic", ""),
                "Article URL": f.get("Source URL", ""),
                "Article HTTP Status": article.get("HTTP Status", ""),
                "Article Overall Status": article.get("Overall Status", ""),
                "Issue Status": f.get("Status", ""),
                "Issue Type": f.get("Rule", ""),
                "Issue Details": f.get("Why", ""),
                "Problem Link": "",
                "Anchor Text": "",
                "Link Type": "",
                "Link HTTP Status": "",
                "Final Destination": "",
                "Redirect Count": "",
                "Redirect Chain": "",
                "Link Rel": "",
                "Evidence": f.get("Evidence", ""),
                "Responsible": f.get("Responsible", ""),
            })

    # Exact problematic links: one row per wrong link.
    if not links_df.empty:
        bad_links = links_df[links_df["Link Status"] != "PASS"].copy()

        for _, l in bad_links.iterrows():
            article = article_lookup.get(l["Source URL"], {})
            code = l.get("Target HTTP Status", "")
            redirects = l.get("Target Redirect Count", 0)

            if code in (404, 410):
                issue_type = "Broken Link"
                issue_status = "FAIL"
                details = f"The link returns HTTP {code}."
            elif code is None or pd.isna(code):
                issue_type = "Unverified Link"
                issue_status = "REVIEW"
                details = "The target URL could not be verified."
            elif isinstance(code, (int, float)) and code >= 500:
                issue_type = "Target Server Error"
                issue_status = "REVIEW"
                details = f"The target returned HTTP {int(code)}."
            elif bool(l.get("Internal", False)) and redirects and redirects > 0:
                issue_type = "Internal Redirect Link"
                issue_status = "REVIEW"
                details = (
                    "The internal link points to an old/redirecting URL. "
                    "Update the article link to the final destination."
                )
            else:
                issue_type = "Link Issue"
                issue_status = l.get("Link Status", "REVIEW")
                details = l.get("Link Reason", "")

            issue_rows.append({
                "Title/Topic": l.get("Title/Topic", ""),
                "Article URL": l.get("Source URL", ""),
                "Article HTTP Status": article.get("HTTP Status", ""),
                "Article Overall Status": article.get("Overall Status", ""),
                "Issue Status": issue_status,
                "Issue Type": issue_type,
                "Issue Details": details,
                "Problem Link": l.get("Target URL", ""),
                "Anchor Text": l.get("Anchor Text", ""),
                "Link Type": "Internal" if bool(l.get("Internal", False)) else "External",
                "Link HTTP Status": l.get("Target HTTP Status", ""),
                "Final Destination": l.get("Target Final URL", ""),
                "Redirect Count": l.get("Target Redirect Count", ""),
                "Redirect Chain": l.get("Target Redirect Chain", ""),
                "Link Rel": l.get("Rel", ""),
                "Evidence": l.get("Link Reason", ""),
                "Responsible": "SEO / Content" if bool(l.get("Internal", False)) else "Content / SEO",
            })

    issues_df = pd.DataFrame(issue_rows)

    if issues_df.empty:
        return pd.DataFrame(columns=[
            "Title/Topic", "Article URL", "Article HTTP Status",
            "Article Overall Status", "Issue Status", "Issue Type",
            "Issue Details", "Problem Link", "Anchor Text", "Link Type",
            "Link HTTP Status", "Final Destination", "Redirect Count",
            "Redirect Chain", "Link Rel", "Evidence", "Responsible"
        ])

    # Sort the most important items first.
    priority = {"FAIL": 0, "REVIEW": 1}
    issues_df["_priority"] = issues_df["Issue Status"].map(priority).fillna(9)
    issues_df = issues_df.sort_values(
        ["_priority", "Title/Topic", "Issue Type", "Problem Link"],
        ascending=[True, True, True, True]
    ).drop(columns=["_priority"])

    return issues_df.reset_index(drop=True)


def save_checkpoint(article_rows, finding_rows, link_rows):
    issues_df = build_issues_only(article_rows, finding_rows, link_rows)
    content_qa_df = build_content_qa_sheet(finding_rows)

    with pd.ExcelWriter(CHECKPOINT_FILE, engine="openpyxl") as writer:
        issues_df.to_excel(writer, sheet_name="Issues Only", index=False)
        content_qa_df.to_excel(writer, sheet_name="Content QA", index=False)

        for sheet_name in ["Issues Only", "Content QA"]:
            ws = writer.book[sheet_name]
            ws.freeze_panes = "A2"
            ws.auto_filter.ref = ws.dimensions
            for cell in ws[1]:
                cell.font = cell.font.copy(bold=True)
            for row in ws.iter_rows(min_row=2):
                for cell in row:
                    cell.alignment = cell.alignment.copy(vertical="top", wrap_text=True)

        issue_widths = {
            "A": 38, "B": 65, "C": 18, "D": 20, "E": 14, "F": 28,
            "G": 58, "H": 70, "I": 38, "J": 14, "K": 18, "L": 70,
            "M": 16, "N": 24, "O": 16, "P": 58, "Q": 22
        }
        for col, width in issue_widths.items():
            writer.book["Issues Only"].column_dimensions[col].width = width

        content_widths = {
            "A": 38, "B": 65, "C": 12, "D": 24, "E": 90, "F": 75,
            "G": 32, "H": 70, "I": 22, "J": 65, "K": 28
        }
        for col, width in content_widths.items():
            writer.book["Content QA"].column_dimensions[col].width = width

# ============================================================
# SITE-WIDE ANALYSIS
# ============================================================

def build_sitewide_analysis(links_df, total_articles):
    findings = []

    if links_df.empty:
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()

    internal_df = links_df[links_df["Internal"] == True].copy()

    target_summary = (
        internal_df
        .groupby("Target URL")
        .agg(
            Articles_Linking=("Source URL", "nunique"),
            Total_Links=("Target URL", "size"),
            Unique_Anchors=("Anchor Text", "nunique")
        )
        .reset_index()
    )

    target_summary["Article Share"] = (
        target_summary["Articles_Linking"]
        / max(total_articles, 1)
    )

    target_summary = target_summary.sort_values(
        ["Articles_Linking", "Total_Links"],
        ascending=False
    )

    for _, row in target_summary.iterrows():
        share = float(row["Article Share"])

        if share >= SITE_TARGET_SHARE_FAIL:
            status = "FAIL"
        elif share >= SITE_TARGET_SHARE_REVIEW:
            status = "REVIEW"
        else:
            continue

        findings.append({
            "Rule": "Site-wide Target Concentration",
            "Status": status,
            "Why": "The same internal target is linked from an unusually large share of audited articles.",
            "Evidence": (
                f"{row['Target URL']} | "
                f"Articles={int(row['Articles_Linking'])} | "
                f"Share={share:.1%} | "
                f"Total Links={int(row['Total_Links'])}"
            ),
            "Responsible": "SEO"
        })

    internal_df["Anchor Normalized"] = (
        internal_df["Anchor Text"]
        .fillna("")
        .str.strip()
        .str.lower()
    )

    usable = internal_df[
        internal_df["Anchor Normalized"] != ""
    ].copy()

    anchor_target = (
        usable
        .groupby(["Anchor Normalized", "Target URL"])
        .size()
        .reset_index(name="Count")
    )

    anchor_totals = (
        usable
        .groupby("Anchor Normalized")
        .size()
        .reset_index(name="Anchor Total")
    )

    anchor_target = anchor_target.merge(
        anchor_totals,
        on="Anchor Normalized",
        how="left"
    )

    anchor_target["Target Share"] = (
        anchor_target["Count"]
        / anchor_target["Anchor Total"]
    )

    anchor_target = anchor_target.sort_values(
        "Count",
        ascending=False
    )

    for _, row in anchor_target.iterrows():
        if int(row["Anchor Total"]) < 20:
            continue

        share = float(row["Target Share"])
        count = int(row["Count"])

        if share >= SITE_ANCHOR_TARGET_SHARE_FAIL and count >= 100:
            status = "FAIL"
        elif share >= SITE_ANCHOR_TARGET_SHARE_REVIEW and count >= 50:
            status = "REVIEW"
        else:
            continue

        findings.append({
            "Rule": "Site-wide Exact Anchor Concentration",
            "Status": status,
            "Why": "The same anchor text points overwhelmingly to the same destination across many articles.",
            "Evidence": (
                f"Anchor={row['Anchor Normalized']!r} | "
                f"Target={row['Target URL']} | "
                f"Count={count} | "
                f"Share={share:.1%}"
            ),
            "Responsible": "SEO / Content"
        })

    return (
        target_summary,
        anchor_target,
        pd.DataFrame(findings)
    )

# ============================================================
# RULE LIBRARY
# ============================================================

def build_rule_library():
    data = [
        ["Article Fetch", "Checks whether the article loads successfully.", "404/410 = FAIL; fetch problem = REVIEW", "Backend / SEO"],
        ["Thin Content", "Checks visible article word count.", "<100 FAIL; <250 REVIEW", "Content"],
        ["Internal Blocked Words", "Your internal prohibited words.", "Any match = FAIL", "Content / Editor"],
        ["Suspicious / Unexpected Terms", "Looks for unusual gambling, adult, pharma, profanity or injected-content terms and shows their context.", "Any match = REVIEW; context required", "Content / Backend"],
        ["Keyword Repetition", "Non-stopword concentration heuristic using count + density.", "20+ and 2%+ REVIEW; 35+ and 3.5%+ FAIL", "Content / SEO"],
        ["Repeated Phrases", "Repeated five-word phrases excluding boilerplate.", "8+ REVIEW; 15+ FAIL", "Content / SEO"],
        ["Entity Accuracy", "Near-duplicate entity names: buildings, projects, communities, developers, companies and places.", "88%+ REVIEW; 96%+ FAIL", "Content / Editor"],
        ["Official-Source Content QA", "AI-assisted factual, entity, grammar, image ALT/caption and search-intent review with web research.", "FAIL only with proof/content error; REVIEW if official evidence is insufficient; PASS when official source confirms", "Content / Editor"],
        ["Meta Robots", "Checks noindex.", "noindex = REVIEW", "SEO / Backend"],
        ["Canonical", "Checks missing/different canonical.", "Mismatch/missing = REVIEW", "SEO / Backend"],
        ["H1", "Checks missing/multiple H1.", "Not exactly 1 = REVIEW", "Content / SEO"],
        ["Hidden Text / Hidden Links", "Checks static hidden HTML text/links.", "Detected = REVIEW", "Backend / SEO"],
        ["Link Density", "Links per 1,000 words.", "40+ REVIEW; 70+ FAIL", "SEO / Content"],
        ["Generic Anchor Text", "Looks for click here/read more style anchors.", "Detected = REVIEW", "Content / SEO"],
        ["Empty Anchor Text", "Links with no visible anchor.", "Detected = REVIEW", "Content / SEO"],
        ["Repeated Target in Same Article", "Same target repeated within article.", "4+ REVIEW; 8+ FAIL", "SEO / Content"],
        ["Repeated Anchor in Same Article", "Same anchor repeated within article.", "4+ REVIEW; 8+ FAIL", "SEO / Content"],
        ["Broken Links", "Article-body links returning 404/410.", "Any = FAIL", "Content / SEO"],
        ["Internal Redirect Links", "Internal links pointing to redirecting URLs.", "Any = REVIEW", "SEO / Content"],
        ["Site-wide Target Concentration", "One target linked from a large share of articles.", "20%+ REVIEW; 50%+ FAIL", "SEO"],
        ["Site-wide Exact Anchor Concentration", "Same exact anchor points to same URL site-wide.", "70%+ REVIEW; 90%+ FAIL with minimum counts", "SEO / Content"],
    ]

    return pd.DataFrame(
        data,
        columns=["Rule", "What It Checks", "Logic", "Responsible"]
    )

# ============================================================
# MAIN
# ============================================================

def run_audit(input_file, output_file, limit=None, ai_content=None):
    if ai_content is None:
        ai_content = AI_CONTENT_QA_DEFAULT

    if ai_content and not OPENAI_API_KEY:
        raise RuntimeError(
            "Official-source Content QA is enabled but OPENAI_API_KEY is not set. "
            "Set OPENAI_API_KEY, or explicitly use --no-ai-content for the legacy non-research checks."
        )

    print(f"Reading: {input_file}")
    print(f"Official-source AI Content QA: {'ON' if ai_content else 'OFF'}")

    df = pd.read_excel(input_file)

    if URL_COLUMN not in df.columns:
        raise ValueError(
            f"Column '{URL_COLUMN}' not found. Available columns: {list(df.columns)}"
        )

    if TITLE_COLUMN not in df.columns:
        df[TITLE_COLUMN] = ""

    work = df[[TITLE_COLUMN, URL_COLUMN]].copy()
    work[URL_COLUMN] = work[URL_COLUMN].astype(str).str.strip()

    work = work[
        work[URL_COLUMN].str.match(r"^https?://", na=False)
    ].copy()

    work[URL_COLUMN] = work[URL_COLUMN].map(normalize_url)

    work = work[
        work[URL_COLUMN].map(is_internal)
        & work[URL_COLUMN].map(is_mybayut_article)
    ].copy()

    work = work.drop_duplicates(subset=[URL_COLUMN])

    if limit:
        work = work.head(limit)

    total = len(work)
    print(f"Unique MyBayut articles to audit: {total:,}")

    s = build_session()

    article_rows = []
    finding_rows = []
    link_rows = []

    target_cache = {}

    for i, row in enumerate(work.itertuples(index=False), start=1):
        article_title = clean_text(getattr(row, "_0"))
        source_url = clean_text(getattr(row, "_1"))

        print(f"[{i:,}/{total:,}] {source_url}")

        result = fetch(s, source_url)

        if not result["ok"]:
            add_finding(
                finding_rows,
                article_title,
                source_url,
                "Article Fetch",
                "REVIEW",
                "Could not fetch the article.",
                result["error"],
                "Backend / SEO"
            )

            article_rows.append({
                "Title/Topic": article_title,
                "Source URL": source_url,
                "HTTP Status": None,
                "Final URL": "",
                "Redirect Count": 0,
                "Word Count": 0,
                "Body Links": 0,
                "Internal Links": 0,
                "External Links": 0,
                "Overall Status": "REVIEW",
                "Reasons": "Article Fetch",
            })
            continue

        r = result["response"]

        if r.status_code in (404, 410):
            add_finding(
                finding_rows,
                article_title,
                source_url,
                "Article Fetch",
                "FAIL",
                f"Source article returns HTTP {r.status_code}.",
                "",
                "Backend / SEO"
            )

            article_rows.append({
                "Title/Topic": article_title,
                "Source URL": source_url,
                "HTTP Status": r.status_code,
                "Final URL": r.url,
                "Redirect Count": len(r.history),
                "Word Count": 0,
                "Body Links": 0,
                "Internal Links": 0,
                "External Links": 0,
                "Overall Status": "FAIL",
                "Reasons": "Article Fetch",
            })
            continue

        content_type = r.headers.get("content-type", "").lower()
        if "text/html" not in content_type:
            add_finding(
                finding_rows,
                article_title,
                source_url,
                "Article Fetch",
                "REVIEW",
                "The URL did not return normal HTML.",
                content_type,
                "Backend / SEO"
            )
            continue

        soup = BeautifulSoup(r.text, "html.parser")
        body = find_article_body(soup)
        text = visible_text(body)

        page_statuses = []

        content_statuses, word_count = content_checks(
            article_title,
            source_url,
            text,
            finding_rows
        )
        page_statuses.extend(content_statuses)

        entity_statuses = entity_accuracy_checks(
            article_title,
            source_url,
            text,
            finding_rows
        )
        page_statuses.extend(entity_statuses)

        if ai_content:
            try:
                ai_statuses = ai_content_qa_checks(
                    article_title,
                    source_url,
                    text,
                    body,
                    finding_rows
                )
                page_statuses.extend(ai_statuses)
            except Exception as e:
                # Operational failure is visible and explicit; never fabricate a factual QA result.
                add_finding(
                    finding_rows, article_title, source_url,
                    "Content QA: System Error",
                    "REVIEW",
                    "Official-source Content QA could not complete for this article. No factual verdict was fabricated.",
                    f"{type(e).__name__}: {e}",
                    "Content / Backend"
                )
                page_statuses.append("REVIEW")

        technical_statuses, canonical, robots_value, h1s = technical_checks(
            article_title,
            source_url,
            soup,
            finding_rows
        )
        page_statuses.extend(technical_statuses)

        links = extract_links(body, source_url)

        link_statuses = page_link_checks(
            article_title,
            source_url,
            links,
            word_count,
            finding_rows
        )
        page_statuses.extend(link_statuses)

        # Check every unique target only once, then reuse result
        page_checked_links = []

        for link in links:
            target = link["Target URL"]

            if target not in target_cache:
                target_result = fetch(s, target)

                if target_result["ok"]:
                    tr = target_result["response"]
                    target_cache[target] = {
                        "Target HTTP Status": tr.status_code,
                        "Target Final URL": tr.url,
                        "Target Redirect Count": len(tr.history),
                        "Target Redirect Chain": target_result["redirect_chain"],
                        "Target Error": "",
                    }
                else:
                    target_cache[target] = {
                        "Target HTTP Status": None,
                        "Target Final URL": "",
                        "Target Redirect Count": 0,
                        "Target Redirect Chain": "",
                        "Target Error": target_result["error"],
                    }

            link.update(target_cache[target])

            status_code = link["Target HTTP Status"]
            redirect_count = link["Target Redirect Count"]

            if status_code in (404, 410):
                link["Link Status"] = "FAIL"
                link["Link Reason"] = f"Broken link: HTTP {status_code}"
            elif status_code is None:
                link["Link Status"] = "REVIEW"
                link["Link Reason"] = "Target could not be verified."
            elif status_code >= 500:
                link["Link Status"] = "REVIEW"
                link["Link Reason"] = f"Server error HTTP {status_code}"
            elif link["Internal"] and redirect_count > 0:
                link["Link Status"] = "REVIEW"
                link["Link Reason"] = "Internal URL redirects; update link to final URL."
            else:
                link["Link Status"] = "PASS"
                link["Link Reason"] = "Target resolved successfully."

            link["Title/Topic"] = article_title
            page_checked_links.append(link)
            link_rows.append(link)

        broken = [
            x for x in page_checked_links
            if x["Link Status"] == "FAIL"
        ]

        status = "FAIL" if broken else "PASS"

        add_finding(
            finding_rows,
            article_title,
            source_url,
            "Broken Links",
            status,
            "Checks article-body links returning 404 or 410.",
            " | ".join(
                f"{x['Anchor Text']!r} -> {x['Target URL']} ({x['Target HTTP Status']})"
                for x in broken[:10]
            ),
            "Content / SEO"
        )

        page_statuses.append(status)

        internal_redirects = [
            x for x in page_checked_links
            if x["Internal"] and x["Target Redirect Count"] > 0
        ]

        status = "REVIEW" if internal_redirects else "PASS"

        add_finding(
            finding_rows,
            article_title,
            source_url,
            "Internal Redirect Links",
            status,
            "Checks internal article links that still point to redirecting URLs.",
            " | ".join(
                f"{x['Target URL']} -> {x['Target Final URL']}"
                for x in internal_redirects[:10]
            ),
            "SEO / Content"
        )

        page_statuses.append(status)

        # Overall FAIL is reserved for stronger technical/editorial failures.
        source_findings = [
            f for f in finding_rows
            if f["Source URL"] == source_url
        ]
        critical_fail_rules = {
            "Article Fetch",
            "Broken Links",
            "Internal Blocked Words",
        }
        has_critical_fail = any(
            f["Status"] == "FAIL" and f["Rule"] in critical_fail_rules
            for f in source_findings
        )
        has_any_review_or_fail = any(
            f["Status"] in {"REVIEW", "FAIL"}
            for f in source_findings
        )

        if has_critical_fail:
            overall_status = "FAIL"
        elif has_any_review_or_fail:
            overall_status = "REVIEW"
        else:
            overall_status = "PASS"

        article_findings = [
            f["Rule"]
            for f in finding_rows
            if f["Source URL"] == source_url
            and f["Status"] != "PASS"
        ]

        article_rows.append({
            "Title/Topic": article_title,
            "Source URL": source_url,
            "HTTP Status": r.status_code,
            "Final URL": r.url,
            "Redirect Count": len(r.history),
            "Redirect Chain": result["redirect_chain"],
            "Word Count": word_count,
            "Body Links": len(links),
            "Internal Links": sum(1 for x in links if x["Internal"]),
            "External Links": sum(1 for x in links if not x["Internal"]),
            "Canonical": canonical,
            "Robots": robots_value,
            "H1 Count": len(h1s),
            "Overall Status": overall_status,
            "Reasons": " | ".join(article_findings),
        })

        if i % SAVE_EVERY == 0:
            print(f"Saving checkpoint at article {i:,} ...")
            save_checkpoint(
                article_rows,
                finding_rows,
                link_rows
            )

        if SLEEP_BETWEEN_ARTICLES:
            time.sleep(SLEEP_BETWEEN_ARTICLES)

    issues_df = build_issues_only(
        article_rows,
        finding_rows,
        link_rows
    )

    print(f"Writing issues-only Excel: {output_file}")
    print(f"Actionable issue rows: {len(issues_df):,}")

    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        issues_df.to_excel(
            writer,
            sheet_name="Issues Only",
            index=False
        )

        content_qa_df = build_content_qa_sheet(finding_rows)
        content_qa_df.to_excel(
            writer,
            sheet_name="Content QA",
            index=False
        )

        ws = writer.book["Issues Only"]
        ws.freeze_panes = "A2"
        ws.auto_filter.ref = ws.dimensions

        # Readable widths for long URLs and issue explanations.
        widths = {
            "A": 38,  # title
            "B": 65,  # article URL
            "C": 18,
            "D": 20,
            "E": 14,
            "F": 28,
            "G": 58,
            "H": 70,  # problem link
            "I": 38,  # anchor
            "J": 14,
            "K": 18,
            "L": 70,  # final destination
            "M": 16,
            "N": 24,
            "O": 16,
            "P": 58,
            "Q": 22,
        }
        for col, width in widths.items():
            ws.column_dimensions[col].width = width

        # Header + wrapped rows.
        from openpyxl.styles import Font, PatternFill, Alignment

        header_fill = PatternFill("solid", fgColor="1F4E78")
        fail_fill = PatternFill("solid", fgColor="F4CCCC")
        review_fill = PatternFill("solid", fgColor="FFF2CC")

        for cell in ws[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = header_fill
            cell.alignment = Alignment(
                vertical="center",
                horizontal="center",
                wrap_text=True
            )

        for row_idx in range(2, ws.max_row + 1):
            status = ws.cell(row_idx, 5).value  # Issue Status
            if status == "FAIL":
                ws.cell(row_idx, 5).fill = fail_fill
            elif status == "REVIEW":
                ws.cell(row_idx, 5).fill = review_fill

            for cell in ws[row_idx]:
                cell.alignment = Alignment(
                    vertical="top",
                    wrap_text=True
                )

        ws.row_dimensions[1].height = 32

        cws = writer.book["Content QA"]
        cws.freeze_panes = "A2"
        cws.auto_filter.ref = cws.dimensions
        content_widths = {
            "A": 38, "B": 65, "C": 12, "D": 24, "E": 90, "F": 75,
            "G": 32, "H": 70, "I": 22, "J": 65, "K": 28
        }
        for col, width in content_widths.items():
            cws.column_dimensions[col].width = width
        for cell in cws[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = header_fill
            cell.alignment = Alignment(vertical="center", horizontal="center", wrap_text=True)
        for row_idx in range(2, cws.max_row + 1):
            status = cws.cell(row_idx, 3).value
            if status == "FAIL":
                cws.cell(row_idx, 3).fill = fail_fill
            elif status == "REVIEW":
                cws.cell(row_idx, 3).fill = review_fill
            for cell in cws[row_idx]:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
        cws.row_dimensions[1].height = 32

    print("\nDONE")
    print(f"Output: {Path(output_file).resolve()}")
    print(
        "The workbook contains an Issues Only sheet plus a Content QA sheet. "
        "Content QA includes PASS/REVIEW/FAIL, natural-language results, official source URLs and suggested fixes. "
        "For link issues, the exact URL, anchor, HTTP status, final destination and redirect chain are included."
    )

# ============================================================
# COMMAND LINE
# ============================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Full MyBayut spam and internal-link audit"
    )

    parser.add_argument(
        "--input",
        default=INPUT_FILE,
        help="Input Excel file"
    )

    parser.add_argument(
        "--output",
        default=OUTPUT_FILE,
        help="Output Excel file"
    )

    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Audit only first N articles for testing"
    )

    ai_group = parser.add_mutually_exclusive_group()
    ai_group.add_argument(
        "--ai-content",
        dest="ai_content",
        action="store_true",
        help="Enable official-source AI Content QA (requires OPENAI_API_KEY)"
    )
    ai_group.add_argument(
        "--no-ai-content",
        dest="ai_content",
        action="store_false",
        help="Disable AI Content QA and use legacy deterministic checks only"
    )
    parser.set_defaults(ai_content=None)

    args = parser.parse_args()

    run_audit(
        input_file=args.input,
        output_file=args.output,
        limit=args.limit,
        ai_content=args.ai_content
    )
